create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  customer_name text not null,
  customer_phone text not null,
  delivery_method text not null check (delivery_method in ('delivery', 'pickup')),
  address text,
  neighborhood text,
  items jsonb not null default '[]'::jsonb,
  subtotal integer not null check (subtotal >= 0),
  delivery_fee integer check (delivery_fee >= 0),
  total integer not null check (total >= 0),
  payment_method text not null check (payment_method in ('pix', 'card', 'cash')),
  payment_label text not null,
  change_for text,
  notes text,
  status text not null default 'Novo' check (
    status in (
      'Novo',
      'Em preparo',
      'Saiu para entrega',
      'Finalizado',
      'Cancelado'
    )
  ),
  whatsapp_business_phone text not null default '5562991102715',
  whatsapp_payload jsonb,
  constraint orders_items_array check (jsonb_typeof(items) = 'array')
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);

alter table public.orders enable row level security;

alter table public.orders alter column delivery_fee drop not null;

drop policy if exists "orders_public_insert" on public.orders;
drop policy if exists "orders_public_select" on public.orders;
drop policy if exists "orders_public_update_status" on public.orders;

create policy "orders_public_insert"
on public.orders
for insert
to anon
with check (true);

create policy "orders_public_select"
on public.orders
for select
to anon
using (true);

create policy "orders_public_update_status"
on public.orders
for update
to anon
using (true)
with check (
  status in (
    'Novo',
    'Em preparo',
    'Saiu para entrega',
    'Finalizado',
    'Cancelado'
  )
);
