create extension if not exists pgcrypto;

create table if not exists public.store_settings (
  id text primary key,
  status text not null default 'open' check (status in ('open', 'closed')),
  updated_at timestamptz not null default now()
);

insert into public.store_settings (id, status)
values ('main', 'open')
on conflict (id) do nothing;

alter table public.store_settings enable row level security;

drop policy if exists "store_settings_public_select" on public.store_settings;
drop policy if exists "store_settings_public_update" on public.store_settings;

create policy "store_settings_public_select"
on public.store_settings
for select
to anon, authenticated
using (id = 'main');

create policy "store_settings_public_update"
on public.store_settings
for update
to anon, authenticated
using (id = 'main')
with check (id = 'main' and status in ('open', 'closed'));

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'store_settings'
  ) then
    alter publication supabase_realtime add table public.store_settings;
  end if;
end
$$;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  customer_name text not null,
  customer_phone text not null,
  delivery_method text not null check (delivery_method in ('delivery', 'pickup')),
  address text,
  neighborhood text,
  items jsonb not null default '[]'::jsonb,
  subtotal integer not null check (subtotal >= 0),
  delivery_fee integer check (delivery_fee >= 0),
  total integer not null check (total >= 0),
  payment_method text not null check (payment_method in ('pix', 'card', 'cash')),
  payment_label text not null,
  change_for text,
  notes text,
  status text not null default 'Novo' check (
    status in (
      'Novo',
      'Em preparo',
      'Saiu para entrega',
      'Finalizado',
      'Cancelado'
    )
  ),
  whatsapp_business_phone text not null default '5562991102715',
  whatsapp_payload jsonb,
  constraint orders_items_array check (jsonb_typeof(items) = 'array')
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);

alter table public.orders enable row level security;

alter table public.orders alter column delivery_fee drop not null;

alter table public.orders
  add column if not exists printed_at timestamptz,
  add column if not exists print_status text,
  add column if not exists print_attempts integer not null default 0,
  add column if not exists print_error text,
  add column if not exists print_updated_at timestamptz;

alter table public.orders alter column print_status set default 'pending';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_print_status_check'
      and conrelid = 'public.orders'::regclass
  ) then
    alter table public.orders
      add constraint orders_print_status_check
      check (print_status is null or print_status in ('pending', 'printing', 'printed', 'failed'));
  end if;
end
$$;

create or replace function public.claim_order_print(p_order_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  affected_rows integer;
begin
  update public.orders
  set
    print_status = 'printing',
    print_attempts = coalesce(print_attempts, 0) + 1,
    print_error = null,
    print_updated_at = now()
  where id = p_order_id
    and printed_at is null
    and (
      print_status is distinct from 'printing'
      or print_updated_at < now() - interval '2 minutes'
    );

  get diagnostics affected_rows = row_count;
  return affected_rows > 0;
end;
$$;

create or replace function public.complete_order_print(p_order_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.orders
  set
    printed_at = now(),
    print_status = 'printed',
    print_error = null,
    print_updated_at = now()
  where id = p_order_id;
$$;

create or replace function public.fail_order_print(p_order_id uuid, p_error text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.orders
  set
    print_status = 'failed',
    print_error = left(coalesce(p_error, 'Falha de impressão'), 500),
    print_updated_at = now()
  where id = p_order_id
    and printed_at is null;
$$;

create or replace function public.register_order_reprint(p_order_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.orders
  set
    print_attempts = coalesce(print_attempts, 0) + 1,
    print_updated_at = now()
  where id = p_order_id;
$$;

revoke all on function public.claim_order_print(uuid) from public;
revoke all on function public.complete_order_print(uuid) from public;
revoke all on function public.fail_order_print(uuid, text) from public;
revoke all on function public.register_order_reprint(uuid) from public;
grant execute on function public.claim_order_print(uuid) to anon, authenticated;
grant execute on function public.complete_order_print(uuid) to anon, authenticated;
grant execute on function public.fail_order_print(uuid, text) to anon, authenticated;
grant execute on function public.register_order_reprint(uuid) to anon, authenticated;

drop policy if exists "orders_public_insert" on public.orders;
drop policy if exists "orders_public_select" on public.orders;
drop policy if exists "orders_public_update_status" on public.orders;

create policy "orders_public_insert"
on public.orders
for insert
to anon
with check (true);

create policy "orders_public_select"
on public.orders
for select
to anon
using (true);

create policy "orders_public_update_status"
on public.orders
for update
to anon
using (true)
with check (
  status in (
    'Novo',
    'Em preparo',
    'Saiu para entrega',
    'Finalizado',
    'Cancelado'
  )
);
